# Generated by Django 5.0.1 on 2024-01-28 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('cook_counter', models.IntegerField(default=0, verbose_name='Счетчик использования')),
            ],
        ),
        migrations.CreateModel(
            name='ProductToRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.product')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('ingridients', models.ManyToManyField(through='cookbook.ProductToRecipe', to='cookbook.product', verbose_name='Ингридиенты')),
            ],
        ),
        migrations.AddField(
            model_name='producttorecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.recipe'),
        ),
        migrations.AlterUniqueTogether(
            name='producttorecipe',
            unique_together={('recipe', 'product')},
        ),
    ]
